version: '3.8'

services:
  app:
    build: .
    container_name: cloud-project
    networks:
      - cloud-second-homework
    environment:
      - SPRING_REDIS_HOST=my_custom_redis
    depends_on:
      - redis

  redis:
    image: ghcr.io/aut-cloud-computing-fall-2024/redis
    container_name: redis-containter
    networks:
      - cloud-second-homework
    volumes:
      - cloud-second-homework:/data
networks:
  cloud-second-homework:

volumes:
  cloud-second-homework: