apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: demo-ns
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
