apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: demo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: mahmoodsaneian/cloud-computing-second-heomwork:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret