apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: demo-ns
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: /mnt/data/redis